Repository sassoftware/viya4-iac-azure, pull requests merged in 2021-05, with the labels that each got.

#148 Allow helper script to be sourced
  files/tools/terraform_env_variable_helper.sh
Labels: bug, documentation

#151 Added prefix validation check and doc updates
  docs/CONFIG-VARS.md
  variables.tf
Labels: bug, documentation, enhancement

#152 Changed kubeconfig flag default value
  variables.tf
Labels: enhancement

#154 Updated diagram
  docs/images/viya4-iac-azure-diag.png
Labels: documentation
