Repository sassoftware/viya4-iac-azure, pull requests merged in 2021-08, with the labels that each got.

#188 use subnet cidrs for nfs exports instead of first vnet cidr
  files/cloud-init/nfs/cloud-config
  main.tf
Labels: bug

#176 Editorial Pass through IaC Docs
  README.md
  docs/CONFIG-VARS.md
  docs/user/AdvancedTerraformUsage.md
  docs/user/AzureHelpTopics.md
  docs/user/TerraformAzureAuthentication.md
  docs/user/TerraformUsage.md
  examples/sample-input-byo.tfvars
  examples/sample-input-defaults.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-ppg.tfvars
  examples/sample-input.tfvars
Labels: documentation

#185 Data Server Updates
  Dockerfile
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-ppg.tfvars
  examples/sample-input.tfvars
  locals.tf
  main.tf
  outputs.tf
  variables.tf
  versions.tf
Labels: documentation, enhancement
