Repository sassoftware/viya4-iac-azure, pull requests merged in 2021-06, with the labels that each got.

#162 Fixed issues identified in #160
  docs/CONFIG-VARS.md
Labels: documentation

#164 Doc has wrong location for terraform_env_variable_helper.sh file
  docs/user/TerraformUsage.md
Labels: documentation, good first issue

#166 nfs vm machine type was incorrect
  examples/sample-input-minimal.tfvars
Labels: bug

#169 Add --output tsv to TF VAR tenant and subscription IDs
  docs/user/AzureHelpTopics.md
Labels: bug, good first issue

#173 Fix security group condition for #156
  main.tf
Labels: bug

#172 Update issue templates
  .github/ISSUE_TEMPLATE/issue--bug-report.md
Labels: enhancement

#174 Fixing nic error.
  modules/azurerm_vm/main.tf
Labels: bug
