Repository sassoftware/viya4-iac-azure, pull requests merged in 2022-08, with the labels that each got.

#242 (IAC-451) Add singlestore support to Azure IAC
  examples/sample-input-singlestore.tfvars
Labels: enhancement

#251 (IAC-451) Use SingleStore for external naming, refine subnet comment
  examples/sample-input-singlestore.tfvars
Labels: documentation

#252 5.2.0 - August 18, 2022
  examples/sample-input-singlestore.tfvars
  files/cloud-init/nfs/cloud-config
Labels: bug, documentation, enhancement

#254 feat: (IAC-583): AKS add support for K8s 1.24
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-ppg.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  modules/azure_aks/variables.tf
  modules/kubeconfig/main.tf
  variables.tf
  versions.tf
Labels: enhancement
