Repository sassoftware/viya4-iac-azure, pull requests merged in 2023-02, with the labels that each got.

#278 feat: (IAC-638): Updated variable description and validation blocks
  variables.tf
Labels: enhancement

#277 feat: (IAC-804): Use device UUID in mount to avoid NFS issues due to restarts
  files/cloud-init/nfs/cloud-config
Labels: enhancement

#280 feat: (IAC-804): Use device UUID in mount to avoid NFS issues due to restarts
  files/cloud-init/nfs/cloud-config
Labels: enhancement

#281 fix: (IAC-905): Change multi-line error message to single line message
  variables.tf
Labels: bug

#282 feat: (IAC-899) Update kubernetes_version to 1.23.12
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-ppg.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  modules/azure_aks/variables.tf
  variables.tf
Labels: documentation, enhancement

#289 feat: (IAC-900): add K8s 1.25 support, set kubectl default to 1.24
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-ppg.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  modules/azure_aks/variables.tf
  variables.tf
Labels: documentation, enhancement
