Repository sassoftware/viya4-iac-azure, pull requests merged in 2023-05, with the labels that each got.

#285 docs: (IAC-910) Update Requirements under the IAC CDS Postgres CONFIG VARS documentation
  docs/CONFIG-VARS.md
Labels: documentation

#310 feat!: (IAC-955) Support Standard value for aks_cluster_sku_tier
  Dockerfile
  README.md
  container-structure-test.yaml
  docs/CONFIG-VARS.md
  modules/azure_aks/variables.tf
  variables.tf
  versions.tf
Labels: enhancement

#311 fix: (IAC-996) Remediate the critical security vulnerabilities
  Dockerfile
  modules/kubeconfig/main.tf
  versions.tf
  vms.tf
Labels: enhancement

#312 feat: (IAC-872) Using GitHub Actions add hadolint, shellcheck and tflint checks
  .github/workflows/linter-analysis.yaml
  .tflint.hcl
  linting-configs/.hadolint.yaml
  linting-configs/.shellcheckrc
  linting-configs/.tflint.hcl
  locals.tf
  main.tf
  modules/azure_aks/main.tf
  modules/azure_aks/outputs.tf
  modules/azurerm_postgresql_flex/main.tf
  modules/azurerm_postgresql_flex/outputs.tf
  modules/azurerm_vm/main.tf
  modules/azurerm_vnet/outputs.tf
  modules/kubeconfig/main.tf
  monitor.tf
  outputs.tf
  variables.tf
  vms.tf
Labels: enhancement

#314 6.6.0 - May 18, 2023
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-ppg.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  modules/azure_aks/variables.tf
  variables.tf
Labels: documentation, enhancement

#315 stagingplus to staging
  .github/workflows/linter-analysis.yaml
  .tflint.hcl
  Dockerfile
  README.md
  container-structure-test.yaml
  docs/CONFIG-VARS.md
  linting-configs/.hadolint.yaml
  linting-configs/.shellcheckrc
  linting-configs/.tflint.hcl
  locals.tf
  main.tf
  modules/azure_aks/main.tf
  modules/azure_aks/outputs.tf
  modules/azure_aks/variables.tf
  modules/azurerm_postgresql_flex/main.tf
  modules/azurerm_postgresql_flex/outputs.tf
  modules/azurerm_vm/main.tf
  modules/azurerm_vnet/outputs.tf
  modules/kubeconfig/main.tf
  monitor.tf
  outputs.tf
  variables.tf
  versions.tf
  vms.tf
Labels: enhancement

#317 7.0.0 - May 25, 2023
  .github/workflows/linter-analysis.yaml
  .tflint.hcl
  Dockerfile
  README.md
  container-structure-test.yaml
  docs/CONFIG-VARS.md
  linting-configs/.hadolint.yaml
  linting-configs/.shellcheckrc
  linting-configs/.tflint.hcl
  locals.tf
  main.tf
  modules/azure_aks/main.tf
  modules/azure_aks/outputs.tf
  modules/azure_aks/variables.tf
  modules/azurerm_postgresql_flex/main.tf
  modules/azurerm_postgresql_flex/outputs.tf
  modules/azurerm_vm/main.tf
  modules/azurerm_vnet/outputs.tf
  modules/kubeconfig/main.tf
  monitor.tf
  outputs.tf
  variables.tf
  versions.tf
  vms.tf
Labels: bug, enhancement
