Repository sassoftware/viya4-iac-azure, pull requests merged in 2023-08, with the labels that each got.

#331 feat: (IAC-1124) add K8s 1.27 support, set kubectl default to 1.26
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-ppg.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  modules/azure_aks/variables.tf
  variables.tf
Labels: enhancement

#334 docs: (IAC-1112) Updated importing azure resource example in Troubleshooting.md
  docs/Troubleshooting.md
Labels: documentation

#335 8.1.0 - August 18, 2023
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-ppg.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  files/cloud-init/jump/cloud-config
  modules/azure_aks/variables.tf
  variables.tf
Labels: documentation, enhancement

#336 docs: (IAC-1084) Update All SAS Documentation links
  docs/CONFIG-VARS.md
Labels: documentation

#290 feat: (IAC-1001) Add ability to set allocation method for public ips of jump and nfs vms
  docs/CONFIG-VARS.md
  modules/azurerm_vm/main.tf
  modules/azurerm_vm/variables.tf
  variables.tf
  vms.tf
Labels: documentation, enhancement
