Repository sassoftware/viya4-iac-azure, pull requests merged in 2023-10, with the labels that each got.

#297 feat: (IAC-950) Add the possibility to specify private dns zone resource id to use for AKS private cluster
  docs/CONFIG-VARS.md
  main.tf
  modules/azure_aks/main.tf
  modules/azure_aks/variables.tf
  variables.tf
Labels: documentation, enhancement

#341 fix: (IAC-1072) Enabling North-South traffic
  outputs.tf
Labels: bug

#344 feat: (IAC-1191) Remediate the security vulnerabilities
  Dockerfile
Labels: enhancement
