Repository sassoftware/viya4-iac-azure, pull requests merged in 2025-04, with the labels that each got.

#476 docs: add TOC to README.md
  README.md
Labels: documentation

#483 10.3.0 - April 16, 2025
  .github/workflows/container-structure-test.yml
  .github/workflows/linter-analysis.yml
  .gitignore
  Dockerfile
  Dockerfile.terratest
  README.md
  container-structure-test.yaml
  docs/CONFIG-VARS.md
  docs/user/AzureHelpTopics.md
  docs/user/TestingPhilosophy.md
  examples/sample-input-byo.tfvars
  examples/sample-input-connect.tfvars
  examples/sample-input-ha.tfvars
  examples/sample-input-minimal.tfvars
  examples/sample-input-postgres.tfvars
  examples/sample-input-ppg.tfvars
  examples/sample-input-singlestore.tfvars
  examples/sample-input.tfvars
  main.tf
  modules/aks_node_pool/main.tf
  modules/aks_node_pool/variables.tf
  modules/azure_aks/main.tf
  modules/azure_aks/variables.tf
  test/default_unit_test.go
  test/defaultplan/admin_test.go
  test/defaultplan/defaults_test.go
  test/defaultplan/location_test.go
  test/defaultplan/network_test.go
  test/defaultplan/nfs_test.go
  test/defaultplan/node_pools_test.go
  test/defaultplan/output_test.go
  test/defaultplan/storage_test.go
  test/defaultplan/subnets_test.go
  test/helpers.go
  test/helpers/json_path.go
  test/helpers/plan_cache.go
  test/helpers/test_case.go
  test/helpers/validation.go
  test/non_default_unit_test.go
  test/nondefaultplan/acr_test.go
  test/nondefaultplan/azure_policy_test.go
  test/nondefaultplan/netapp_test.go
  test/nondefaultplan/postgres_test.go
  test/nondefaultplan/rbac_test.go
  test/terratest_docker_entrypoint.sh
  test/testoutput/parse_results.go
  variables.tf
  versions.tf
Labels: bug, documentation, enhancement

#484 docs: (PSKD-1500) update CONTRIBUTING.md with new expectations
  CONTRIBUTING.md
Labels: documentation

#487 fix: remove PLPGSQL azure extension (PSKD-1642)
  docs/CONFIG-VARS.md
  variables.tf
Labels: bug

#488 10.3.1 - April 23, 2025
  CONTRIBUTING.md
  docs/CONFIG-VARS.md
  test/nondefaultplan/rbac_test.go
  variables.tf
Labels: bug, documentation

#491 docs: add community-contributed config_vars
  docs/community/community_config_vars.md
Labels: documentation

#490 test: integration test framework, integration tests and updated doc (PSKD-1537)
  Dockerfile.terratest
  docs/user/TerratestDockerUsage.md
  docs/user/TestingPhilosophy.md
  test/defaultapply/default_apply_main_test.go
  test/defaultapply/resource_group_test.go
  test/defaultapply/vm_test.go
  test/go.mod
  test/go.sum
  test/helpers/apply_helper.go
  test/helpers/apply_retrievers.go
  test/helpers/apply_test_case.go
  test/helpers/helper_test.go
  test/helpers/test_case.go
  test/nondefaultapply/non_default_apply_main_test.go
  test/terratest_docker_entrypoint.sh
Labels: test

#489 chore(deps): update vm image to ubuntu 22.04 (PSKD-1572)
  docs/CONFIG-VARS.md
  modules/azurerm_vm/main.tf
  modules/azurerm_vm/variables.tf
Labels: chore
