Repository sassoftware/viya4-iac-azure, pull requests merged in 2025-05, with the labels that each got.

#451 feat: experimental spot node pools
  docs/community/community_config_vars.md
  main.tf
  modules/aks_node_pool/main.tf
  modules/aks_node_pool/variables.tf
  variables.tf
Labels: enhancement

#493 feat: Adding community option for Azure NetappFiles Volume size control.
  docs/community/community_config_vars.md
  main.tf
  modules/azurerm_netapp/main.tf
  modules/azurerm_netapp/variables.tf
  variables.tf
Labels: enhancement

#496 chore: update workflows to point to main
  .github/dependabot.yml
  .github/workflows/conventional-commits.yml
  .github/workflows/linter-analysis.yml
Labels: chore

#477 fix: Adding permission management for BYO networks #450
  docs/CONFIG-VARS.md
  docs/user/BYOnetwork.md
  locals.tf
  main.tf
  modules/azurerm_vnet/main.tf
  modules/azurerm_vnet/variables.tf
  variables.tf
Labels: bug

#502 fix: IaC Azure requires 'temporary_name_for_rotation' during update
  modules/aks_node_pool/main.tf
  modules/azurerm_vm/main.tf
Labels: bug

#504 docs: Updating CONFIG-VARS ssh_public_key
  docs/CONFIG-VARS.md
Labels: documentation
